# Paths
paths:
  scratch_dir: /work/courses/3dv/36
  egtea_dir: ${REPO_ROOT}/egtea_gaze
  ego_topo_data: ${paths.scratch_dir}/ego-topo/data/gtea

# Dataset parameters
dataset:
  train_timestamps: [0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
  val_timestamps: [0.25, 0.5, 0.75]
  n_cores: 2
  splits:
    train: ${paths.ego_topo_data}/split/train_S1.csv
    val: ${paths.ego_topo_data}/split/val_S1.csv
    train_test_splits: ${paths.ego_topo_data}/train_test_splits.json
